### ISSUE TITLE
a chat about plugins

### ISSUE THREAD

**Issue by mattiaerre** [matteofigus/oc-info#3]
Hi @matteofigus as per our quick chat I am interested in understanding how plugin tracking works. I see that you can specify component's required plugins at the package.json oc section level but this is not strictly necessary in order consume a plugin from a component. So, for example, you can create a component that uses a plugin w/o having this plugin listed in the package.json. Also from a registry point of view, there is no way to understand which plugins are installed and there is not even a way to specify them at any configuration level. This is a very flexible and dynamic approach but it would be nice to enforce plugins registered list as well as plugins used in a more explicit way. I am not sure how to achieve this but I'd love to have a, like I said, more explicit way of knowing upfront which plugins are registered (Registry side) and which plugins are needed (Component side); my aim is to enrich my [GraphQL](https://github.com/opencomponents/oc-registry-graphql-express-middleware) endpoint w/ available plugins at the registry level.

**Comment by matteofigus** [comment]
Yo @mattiaerre,
1) You must specify components' required plugins at the package.json level. It should be strictly required but it isn't for a bug: https://github.com/opentable/oc/issues/445 (you also volunteered taking care of that? If you can't, I can try to prioritise that).
2) The registry actually specifies the plugins in a registration level: https://github.com/opentable/oc/wiki/Registry#registryregisterplugin--callback - so the registry knows which ones are there, they are just not exposed by its api
3) Consider that exposing the plugins via its API may be not something that would be suitable for each plugin. For instance, at OpenTable we have plugins that handle encryption and security and they shouldn't be exposed via the public API, if we decide to, but possibly only by the "private" UI (the `discovery: true` mode - which perhaps we should rename to something better).
Hopefully this clarifies.

I think the next steps should be:
1) Fix the bug to make the plugins detective work again (I think the detection could actually be moved back to the webpack bundling rather than on the component's execution for performance and effectiveness?)
2) Discuss about to expose this in the API level (at the point, we can discuss about how to do it via the GraphQL endpoint as a consequence).

What do you think?

**Comment by mattiaerre** [comment]
Hi @matteofigus I see,
I remembered that issue; sorry about that, I'll look into it asap 😉 re 2. I see your point, exposing the info that a plugin has been installed doesn't mean exposing the plugin functionality itself although; or am I missing something? Agree re next steps; I'll first have a look at the bug so that I can better understand what it takes in order to expose plugins info 👍

**Comment by mattiaerre** [comment]
closing this issue because of https://github.com/opentable/oc/issues/512
